// <auto-generated />
using E_Saldytuvas.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace E_Saldytuvas.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E_Saldytuvas.Server.Models.CookedMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("RecipeId");

                    b.Property<double>("Size");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("CookedMeals");
                });

            modelBuilder.Entity("E_Saldytuvas.Server.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<int?>("MeasureId");

                    b.Property<string>("Name");

                    b.Property<int?>("RecipeId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MeasureId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("E_Saldytuvas.Server.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("E_Saldytuvas.Server.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("E_Saldytuvas.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("E_Saldytuvas.Server.Models.CookedMeal", b =>
                {
                    b.HasOne("E_Saldytuvas.Server.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");

                    b.HasOne("E_Saldytuvas.Server.Models.User")
                        .WithMany("CookedMeals")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("E_Saldytuvas.Server.Models.Ingredient", b =>
                {
                    b.HasOne("E_Saldytuvas.Server.Models.Measure", "Measure")
                        .WithMany()
                        .HasForeignKey("MeasureId");

                    b.HasOne("E_Saldytuvas.Server.Models.Recipe")
                        .WithMany("Igredients")
                        .HasForeignKey("RecipeId");

                    b.HasOne("E_Saldytuvas.Server.Models.User")
                        .WithMany("Ingredients")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("E_Saldytuvas.Server.Models.Recipe", b =>
                {
                    b.HasOne("E_Saldytuvas.Server.Models.User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
